name: Build
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'include/**'
      - 'tools/src/**'
      - 'Makefile'
      - '*.mk'
      - '.github/workflows/build.yml'

  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'tools/src/**'
      - 'Makefile'
      - '*.mk'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cc: gcc
          - os: macos-latest
            cc: clang
    env:
      CC: ${{ matrix.cc }}
      CFLAGS: -Os -Wall -Werror
      CSTANDARD: c99
      WEXTRA: 1
      FORTIFY: 3

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Build static library
        run: make static

      - name: Build shared library
        run: make shared

      - name: Compile solsys plugins
        run: make solsys

      - name: Build examples
        run: make examples

      - name: Build benchmarks
        run: make -C benchmark build

  build-cpp:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cxx: g++
          - os: macos-latest
            cxx: clang++
    env:
      CXX: ${{ matrix.cxx }}
      CXXFLAGS: -Os -Wall -Werror
      WEXTRA: 1
      FORTIFY: 3

    steps:
      - uses: actions/checkout@v6
      
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Build static C++ library
        run: make static-cpp

      - name: Build shared C++ library
        run: make shared-cpp
        
      - name: Build C++ examples
        run: make -C examples/cpp


# Reverse build not yet supported in ubuntu-latest
#
#  reverse-build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v6
#    - name: Reverse order build
#      run: make --shuffle=reverse

#  test-calceph:
#    name: Build with CALCEPH support
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#
#      - name: Install dependencies
#        run: |
#           sudo apt-get update -q -y
#           sudo apt-get install -y libcalceph-dev
#
#      - name: Build
#        env:
#          CALCEPH_SUPPORT: 1
#        run: make solsys

  build-freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    steps:
      - uses: actions/checkout@v6

      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.0"
          prepare: |
            pkg install -y gmake curl devel/pkgconf
          run: |
            echo Building on FreeBSD $(uname -m)
            export CFLAGS=`pkg-config --cflags libcurl`
            export LDFLAGS=`pkg-config --libs libcurl`
            gmake static
            gmake shared

  build-mcu:
    runs-on: ubuntu-latest
    name: Embedded ARM
    steps:
      - uses: actions/checkout@v6

      - uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: Build static library (bare-metal, no-libc)
        # As an example, compile a static library for the RP2350 microcontroller
        run: >
          make CC=arm-none-eabi-gcc WITHOUT_LIBC=1
          CFLAGS="-mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -Os -Wall -Werror"
          static
