name: Example
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - '.github/workflows/example.yml'

  pull_request:
    paths:
      - 'examples/**'
      - '.github/workflows/example.yml'

jobs:
  build:
    name: Check examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prog: [star, high-z, orbital, time, rise-set, moon]

    steps:
    - uses: actions/checkout@v7

    - name: Compile example-${{ matrix.prog }}.c
      run: |
        gcc -c -Wall -Werror -Iinclude examples/c99/example-${{matrix.prog }}.c

    - name: Compile example-${{ matrix.prog }}.cpp
      run: |
        g++ -c -Wall -Werror -Iinclude examples/cpp/example-${{ matrix.prog }}.cpp

